-- Fix Database Schema Mismatch for Supabase Learning Content
-- Use this script in the Supabase SQL Editor if needed manually.

-- 1. Tracks
ALTER TABLE tracks ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;

-- 2. Modules
ALTER TABLE modules ADD COLUMN IF NOT EXISTS module_number VARCHAR(50);
ALTER TABLE modules ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;

-- 3. SubModules
ALTER TABLE sub_modules ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE sub_modules ADD COLUMN IF NOT EXISTS sub_module_number VARCHAR(50);
ALTER TABLE sub_modules ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;

-- 4. Lessons
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS opening_hook TEXT;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS core_explanation TEXT;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS socratic_questions JSONB DEFAULT '[]';
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS real_life_application TEXT;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS key_takeaways JSONB DEFAULT '[]';
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS quiz_questions JSONB DEFAULT '[]';
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS practice_scene_id VARCHAR(255);
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS xp_reward INTEGER DEFAULT 0;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS read_time INTEGER DEFAULT 5;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS is_published BOOLEAN DEFAULT FALSE;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS lesson_number VARCHAR(50);
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS content JSONB;
ALTER TABLE lessons ADD COLUMN IF NOT EXISTS sub_module_id INTEGER REFERENCES sub_modules(id) ON DELETE SET NULL;

-- 5. Market Secrets
ALTER TABLE market_secrets ADD COLUMN IF NOT EXISTS answer_content JSONB DEFAULT '{}';
ALTER TABLE market_secrets ADD COLUMN IF NOT EXISTS answer_html TEXT;
ALTER TABLE market_secrets ADD COLUMN IF NOT EXISTS icon_emoji VARCHAR(10) DEFAULT '🔮';
ALTER TABLE market_secrets ADD COLUMN IF NOT EXISTS xp_reward INTEGER DEFAULT 25;
ALTER TABLE market_secrets ADD COLUMN IF NOT EXISTS sort_order INTEGER DEFAULT 0;
ALTER TABLE market_secrets ADD COLUMN IF NOT EXISTS is_published BOOLEAN DEFAULT FALSE;
ALTER TABLE market_secrets ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- 6. Topic Tags
ALTER TABLE topic_tags ADD COLUMN IF NOT EXISTS display_name VARCHAR(150);
ALTER TABLE topic_tags ADD COLUMN IF NOT EXISTS short_summary TEXT;
ALTER TABLE topic_tags ADD COLUMN IF NOT EXISTS target_type VARCHAR(20) DEFAULT 'chapter';
ALTER TABLE topic_tags ADD COLUMN IF NOT EXISTS target_id INTEGER;
ALTER TABLE topic_tags ADD COLUMN IF NOT EXISTS icon_emoji VARCHAR(10) DEFAULT '📘';
ALTER TABLE topic_tags ADD COLUMN IF NOT EXISTS usage_count INTEGER DEFAULT 0;
ALTER TABLE topic_tags ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ DEFAULT NOW();

-- ✅ All clear!
